name: Release CLI Tool 
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  Build-CLI-Tool: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: `1.18.3`
      - name: Check Go Version 
         run: go version 
      - name: Install Make 
        run: sudo apt-get install -y make 
      - name: Build Tool
        run: make compile 
      - uses: actions/upload-artifact@v3
        with:
          name: cli-images
          path: bin/

  Release-CLI-Tool: 
    if: github.event.base_ref == `refs/head/main`
    needs: [Build-CLI-Tool]
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/download-artifact@v3
        with:
          name: cli-images
          path: cli-images
      - name: List Downloaded Artifacts 
        run: ls cli-images 
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create Release 
        run: gh release create ${{ steps.get_version.outputs.VERSION }} cli-images/linux/microscopeImageProcessor cli-images/windows/microscopeImageProcessor 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}