name: Release CLI Tool 
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  Build-CLI-Tool: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.3' # The Go version to download (if necessary) and use.
      - run: go version
      - name: Install Make 
        run: sudo apt-get install -y make 
      - name: Build Tool
        run: make compile 
      - uses: actions/upload-artifact@v3
        with:
          name: cli-images
          path: bin/

  Release-CLI-Tool: 
    runs-on: ubuntu-latest 
    needs: Build-CLI-Tool
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: cli-images
          path: cli-images
      - name: List Downloaded Artifacts 
        run: ls $PWD/cli-images 
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create Release 
        run: gh release create ${{ steps.get_version.outputs.VERSION }} $PWD/cli-images/linux/microscopeImageProcessor $PWD/cli-images/windows/microscopeImageProcessor.exe 
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}